version: '3'

networks:
  loki:
  tunnel:


services:
  recruit_flow_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: recruit_flow_bot_image
    container_name: recruit_flow_bot_cont
    ports:
      - 3100:3000
    restart: always
    volumes:
      - .env:/recruit_flow_ai/.env
    labels:
      logging: "promtail"
    networks:
      - tunnel
    depends_on:
      - cloudflare_tunnel

  cloudflare_tunnel:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    labels:
      logging: "promtail"
    networks:
      - tunnel

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3200:3000
    restart: unless-stopped
    volumes:
      - ./scripts/loki/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    networks:
      - loki

  loki:
    image: grafana/loki:latest
    ports:
      - 3300:3100
    restart: unless-stopped
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    restart: unless-stopped
    volumes:
      - ./scripts/loki/promtail.yaml:/etc/promtail/docker-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/docker-config.yaml
    networks:
      - loki
    depends_on:
      - loki
