version: '3'
services:
  recruit_flow_bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: recruit_flow_bot_image
    container_name: recruit_flow_bot_cont
    ports:
      - 3100:3000
    restart: always
    env_file:
      - .env
    logging:
      driver: loki
      options:
        loki-url: ${LOKI_URL}
