version: '3.7'

services:
  cv_storage:
    image: quay.io/minio/minio
    volumes:
      - /opt/coxit/cv:/opt/coxit/cv
    ports:
      - 7000:9000
      - 7001:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
      MINIO_SERVER_URL: ${SERVER_URL}
    command: server /opt/coxit/cv --console-address ":9001"
    depends_on:
      - cloudflared_7000_port
      - cloudflared_7001_port
    restart: unless-stopped

  cloudflared_7000_port:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TOKEN_7000_PORT}
    restart: unless-stopped

  cloudflared_7001_port:
    image: cloudflare/cloudflared:latest
    command: tunnel --no-autoupdate run --token ${TOKEN_7001_PORT}
    restart: unless-stopped

