name: Update Version

on:
  pull_request:
    branches:
        - dev
        - main
    paths:
      - 'src/**'
      - 'slack_bot/**'
      

jobs:
  version_update:
    name: Check CVScanAI project version is updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Ensure new version is changed properly
        id: version-changes
        run: |
          git fetch;
          current=$(git branch --show-current);
          git checkout $TARGET_BRANCH;
          
          if [ -f "setup.py" ]; then
            old_version=$(python setup.py -V);
          else
            # TODO: this else part should be deleted on first merge to main
            echo "Setup file does not exist on target branch yet! This should be the very first version update on target branch";
            old_version="0.0.0"
          fi
          git checkout $current;
          new_version=$(python setup.py -V);
          echo "New Version is: $new_version; Old Version is $old_version"
          old_major=$(echo $old_version | awk -F'[.]' '{print $1}');
          new_major=$(echo $new_version | awk -F'[.]' '{print $1}');
          old_minor=$(echo $old_version | awk -F'[.]' '{print $2}');
          new_minor=$(echo $new_version | awk -F'[.]' '{print $2}');
          old_patch=$(echo $old_version | awk -F'[.]' '{print $3}');
          new_patch=$(echo $new_version | awk -F'[.]' '{print $3}');
          if [[ $new_major -lt $old_major ]]; then
            echo "Version's major in the source branch is lower than the one in the targeted branch!";
            exit 1;
          elif [[ $new_major -eq $old_major && $new_minor -lt $old_minor ]]; then
            echo "Version's minor in the source branch is lower than the one in the targeted branch!";
            exit 1;
          elif [[ $new_major -eq $old_major && $new_minor -eq $old_minor && $new_patch -le $old_patch ]]; then
            echo "Version's patch in the source branch is lower than the one in the targeted branch!";
            exit 1;
          fi
        env:
          TARGET_BRANCH: origin/${{ github.base_ref }}
   